apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/publicEndpoints: '[{"port":30769,"protocol":"TCP","serviceName":"jenkins:jenkins","allNodes":true},{"port":32489,"protocol":"TCP","serviceName":"jenkins:jenkins","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"jenkins"},"name":"jenkins","namespace":"jenkins"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"name":"jenkins"},"name":"jenkins"},"spec":{"containers":[{"env":[{"name":"LIMITS_MEMORY","valueFrom":{"resourceFieldRef":{"divisor":"1Mi","resource":"limits.memory"}}},{"name":"JAVA_OPTS","value":"-Xmx$(LIMITS_MEMORY)m
      -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50
      -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85"}],"image":"jenkins/jenkins:lts-alpine","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":12,"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"timeoutSeconds":5},"name":"jenkins","ports":[{"containerPort":8080},{"containerPort":50000}],"readinessProbe":{"failureThreshold":12,"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"timeoutSeconds":5},"resources":{"limits":{"cpu":1,"memory":"1Gi"},"requests":{"cpu":0.5,"memory":"500Mi"}}}],"securityContext":{"fsGroup":1000},"serviceAccountName":"jenkins","terminationGracePeriodSeconds":10}}}}'
  creationTimestamp: "2019-03-13T21:06:08Z"
  generation: 3
  labels:
    name: jenkins
  name: jenkins
  namespace: jenkins
  resourceVersion: "1237448"
  selfLink: /apis/apps/v1beta2/namespaces/jenkins/deployments/jenkins
  uid: d2c48682-45d3-11e9-bce5-00163e02623f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-03-13T21:09:05Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"jenkins-","name":"8080tcp00","protocol":"TCP","sourcePort":0},{"containerPort":50000,"dnsName":"jenkins-","name":"50000tcp00","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        name: jenkins
      name: jenkins
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx$(LIMITS_MEMORY)m -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0
            -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
        - name: LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        image: jenkins/jenkins:lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: 8080tcp00
          protocol: TCP
        - containerPort: 50000
          name: 50000tcp00
          protocol: TCP
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          capabilities: {}
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /srv/jenkins_home
          type: DirectoryOrCreate
        name: vol1
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-03-13T21:07:15Z"
    lastUpdateTime: "2019-03-13T21:07:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-03-13T21:06:08Z"
    lastUpdateTime: "2019-03-13T21:09:05Z"
    message: ReplicaSet "jenkins-695c6fb8d5" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
